deployment:
  tasks:
    - export APPPATH=/home/ceylysas/repositories/CeylonShineTravelWeb
    - export DEPLOYPATH=/home/ceylysas/public_html

    - cd $APPPATH
    - rm -rf .next out
    - npm ci
    - npm run build

    - rsync -av --delete out/ $DEPLOYPATH/
