deployment:
  tasks:
    - export APPPATH=/home/ceylysas/repositories/CeylonShineTravelWeb
    - export NODE_ENV=production

    - cd $APPPATH
    - rm -rf .next
    - npm ci
    - npm run build

    # restart passenger
    - touch tmp/restart.txt
